# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-21 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20181020_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热卖'),
        ),
    ]
