# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-22 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_remove_goods_is_hot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0004_auto_20181020_2010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingcart',
            unique_together=set([('user', 'goods')]),
        ),
    ]
