# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20181022_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='trade.OrderInfo', verbose_name='订单详情'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_mount',
            field=models.FloatField(default=1, verbose_name='订单金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '待支付'), ('TRADE_CLOSED', '交易关闭'), ('TRADE_SUCCESS', '交易成功'), ('TRADE_FINISHED', '交易完成')], default='WAIT_BUYER_PAY', max_length=20, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='支付宝交易号'),
        ),
    ]
